// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfxPO9hg5XXiCHDdaICxHSXCsgi0ZCIpo',
    appId: '1:400297971432:web:01df42b9eaa84fbfaf035d',
    messagingSenderId: '400297971432',
    projectId: 'egypt-fault-map',
    authDomain: 'egypt-fault-map.firebaseapp.com',
    storageBucket: 'egypt-fault-map.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuxh289tBdxTPeBL9R-3XZ3BcKvzl7Ql8',
    appId: '1:400297971432:android:ddd5ff15e64b19c7af035d',
    messagingSenderId: '400297971432',
    projectId: 'egypt-fault-map',
    storageBucket: 'egypt-fault-map.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3LSW7FOuL7h7DKynHpB6lEYowRzA65wg',
    appId: '1:400297971432:ios:709463dbfa979e19af035d',
    messagingSenderId: '400297971432',
    projectId: 'egypt-fault-map',
    storageBucket: 'egypt-fault-map.firebasestorage.app',
    iosBundleId: 'com.example.egyptFaultMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfxPO9hg5XXiCHDdaICxHSXCsgi0ZCIpo',
    appId: '1:400297971432:web:27b64c50080ef107af035d',
    messagingSenderId: '400297971432',
    projectId: 'egypt-fault-map',
    authDomain: 'egypt-fault-map.firebaseapp.com',
    storageBucket: 'egypt-fault-map.firebasestorage.app',
  );
}
